# Generated by Django 3.2.5 on 2023-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_translatorr_numberofappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fromLanguage',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='toLanguage',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
