# Generated by Django 3.2.5 on 2023-05-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230518_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='translatorr',
            name='gender',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
