# Generated by Django 3.2.5 on 2023-05-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appointment_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=17)),
                ('gender', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_Admin',
            field=models.BooleanField(default=False, verbose_name='is Admin'),
        ),
    ]
