# Generated by Django 3.2.5 on 2023-05-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230527_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paidTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
